// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/calendar/create-event': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calendar/create-event.post').default>>>>
    }
    '/api/gifts/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gifts/create.post').default>>>>
    }
    '/api/gifts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gifts/index.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/pdf/export': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pdf/export.post').default>>>>
    }
    '/api/scenario/apply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scenario/apply.post').default>>>>
    }
    '/api/wishlists/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlists/create.post').default>>>>
    }
    '/api/wishlists': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlists/index.get').default>>>>
    }
    '/api/wishlists/respond-invitation': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlists/respond-invitation.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}